### ISSUE TITLE
Windows Virtual Computers (Client OS LON-CL1 thru CL4) are Windows 10 1809 which is no longer supported, and is out of date.  Students are confused and some are frustrated.

### ISSUE THREAD

**Issue by Bobkr01** [MicrosoftLearning/MD-100T00-Windows10#17]
# Module: 00
#### Step: 00

Description of issue
Windows Virtual Computers (Client OS LON-CL1 thru CL4) are Windows 10, version 1809 which is no longer supported, and is out of date.  Students are confused and some are frustrated.  Soon, 1903 will not be supported any more.

Frustration:  Students want to see/use Edge Chromium as well as a 'current' OS version.
Repro steps:

1.
1.
1.

**Comment by BrianHinkelman** [comment]
We are in the process of updating the Modern Desktop track labs, including refreshing the OS - expect to see an announcement on this in the next couple weeks. We understand the concern - the delay in refreshing these was not intentional. However, the lab steps should still work for the VMs provided. Furthermore, the concepts and topics relevant to the MDA track have not fundamentally changed, and students should not be concerned that the version used in the course creates any significant disadvantage when performing the role of the MDA or becoming certified.

**Comment by BrianHinkelman** [comment]
Closed, per Feb 2021 update.
