### ISSUE TITLE
Consecutive vs Out-Of-Order Dependent Labs 

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MD-100T00-Windows10#24]
# Module: 2, 3, 5, & 8

Description of issue:

The labs listed as dependent (2,3,5 -> 8) are 'out of order', Can they be re-ordered such that any dependent labs are consecutive? 

![image](https://user-images.githubusercontent.com/49700217/108293896-a9305380-7149-11eb-905c-93297de4cda6.png)

i.e, instead of Labs 2,3,5 -> 8, could they be sequenced as Labs 2-5, or in a similar fashion?  (1-4, or 10-13?)

The reasoning behind this is that (from a Lab Hosting perspective) where one needs to maintain state/constructs/resources between dependent labs, the current out-of-order sequencing means that an individual module would need to be created to host the work done in Labs 2, 3, then 5, and finally 8.  To a student/instructor who prefers to teach the course in sequence, this could be considered both confusing and potentially prone to errors/mishaps as students end their 'Combined Lab 2,3,5 & 8' module prematurely and lose work they'll need to recreate again.  

It is also possible to avoid the issue altogether by creating a single 'All Labs' module in which the entire course has its state maintained throughout the length of the course, but then we lose out on the benefits of short and easily digestible 1-2 hour individual labs that can be taken at any time/in any order, which is highly desirable  - and it certainly appears some effort was made to insure many of the labs in this course are completely independent of one another.

In any case, in my experience the gold standard is no dependencies at all between lab modules, but when certain aspects simply must be dependent upon one another - it is very desirable to order them sequentially. 

Repro steps:

1.
1.
1.

**Comment by BrianHinkelman** [comment]
Can you clarify "this could be considered both confusing and potentially prone to errors/mishaps as students end their 'Combined Lab 2,3,5 & 8' module prematurely and lose work they'll need to recreate again."  

ALHs should be providing a lab environment that remains persistent throughout the course.  What is the scenario where the student is losing work performed in a previous lab?

**Comment by TesterTesterson1004** [comment]
To clarify:  In the spreadsheet 'Hosting Manifest' for new MD-100, (the screenshot I included) it lists only Lab 8 as having 'predecessor' labs, specifying that Lab 8 relies on work done in labs 2, 3, & 5.   This should indicate that Lab 8 relies on the state of those previous labs and is thus 'dependent' on them.

Any Lab in the manifest that does not include a 'Predecessor' lab thus ought to be considered 'independent' and can be created as an individual lab.  A lab hoster could thus create individual lab modules for labs 1, 4, 6, 7, 9, 10, 11, & 12 since they have no predecessor - and a student could then take the labs in any order, at any time, without the need to save state, or in any way rely on any work done in the previous lab.

However, for Lab 8 (since it relies on that previous work) it would have to be its own separate lab module called (say) 'Module 2,3,5, & 8' which they would need to keep active until the work is done for those labs.

If, for the new MD-100, the 'lab environment must remain persistent throughout the course', then perhaps the actual issue is that the updated Hosting Manifest/Predecessor column is wrong? If this is the case, then it should look like the one for new MD-101.

[MD-101, whose 'Predecessor' columns clearly indicate every lab is dependent on the work from the previous lab, so it would be considered to have no independent labs at all, and would be created as one big 'All Labs' module in which state would be maintained throughout the entire course. ]

![image](https://user-images.githubusercontent.com/49700217/108386548-98bbbf80-71c1-11eb-8710-82addba767bb.png)

**Comment by BrianHinkelman** [comment]
ALHs should be delivering MD-100 and MD-101 as a persistent lab environment from the start to the end. That is not the purpose of the manifest.  There should be no need for anyone to be creating labs, or saving states, or resetting the environment.   The predecessor awareness is so that, in the case of MD-100, in situations where the MCT may skip a lab, there is an impact if 2,3, or 5 is skipped (like for time constraints or student interest) - and what needs to be done is documented in the lab steps themselves.  For, MD-101, dependencies are unavoidable. 

While it may have been prudent to keep these together in self-hosting-related situations, in a persistent environment, there's no need for this with ALH environment.  It is essentially "one big lab environment" - but this doesn't mean that all of the lab steps must be performed at once. The order of the lessons and topics can be based on instructional design, and not forced to follow an order based on the dependencies of the lab steps. The limitation you are describing really should no longer exist. 

If this does not reflect what you are seeing  - if you find yourself having to save states and work with reset environments in the middle of the course - please let us know which ALH you are working with. 

Thanks,
Brian

**Comment by TesterTesterson1004** [comment]
Understood, thanks!
