### ISSUE TITLE
0602 Creating a Storage Space

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-100T00-Windows10#29]
# Module: 06
#### Step: 3

![image](https://user-images.githubusercontent.com/66324487/110847669-0e1b2d00-8262-11eb-8776-efb4c0e8bcea.png)

![image](https://user-images.githubusercontent.com/66324487/110847715-1c694900-8262-11eb-8712-a10907706043.png)

The Clear-Disk command fails as it cannot locate Disk 1. Get-Disk will show disks 0, 2, and 3, but not 1. You can get around this by using diskpart instead which can locate the dynamic disk created in the previous lab (the previous lab doesn't include the dynamic disk popup in Task 4 Step 4) OR you can manually delete the volumes in Disk Manager and then run the Clear-Disk cmdlet from step 3.

**Comment by TesterTesterson1004** [comment]
**Just verifying/confirming behavior:** In a separate repro in a fresh MD-100 lab: As the issue indicates I see the same behavior.

- In the previous 0601 lab, in 'Task 4: Extend a simple volume', the steps 1-4 to Extend - referencing drive E: specifically - lead to a prompt that is otherwise unaccounted for in the instructions indicating that in order to extend that drive, the Basic disk must be converted to Dynamic:

![image](https://user-images.githubusercontent.com/49700217/111080122-2e452900-84ba-11eb-9b0f-19af3377b5bd.png)

- I believe this should be considered expected because we created an F: drive on the same disk earlier in 0601, in Task 3, so the E: no longer has any contiguous space and must be converted to Dynamic.  i.e. _"...a basic disk requires this space to be contiguous. A dynamic disk, OTOH, can contain a spanned volume consisting of several non-contiguous partitions spanning one or more disks..."_

- That then leads to the later issue where the get-disk does not see Dynamic disks, and I do not believe get-disk in Powershell is expected to be able to see Dynamic disks. 


**Solution 1:** As mentioned, one could solve for the issue in 0602/Task 1 by elaborating slightly the instructions to use either diskpart to remove, or else Disk Manager. (and leaving 0601 unmodified except for the addition of the warning to take into account the 'convert to dynamic' dialog box.  

**Solution 2:** A different way to fix for this could also be to change the 0601/Task 4 instructions to reference extending the **F:** drive, rather then E:, since the F: drive still has contiguous unused space upon which to extend and this can thus be accomplished without converting to Dynamic.  One would need to slightly update the 0601/Task 5 instructions to reference the shrunken disk size to 11GB...but then 0602 instructions could be followed unmodified.

**Comment by BrianHinkelman** [comment]
Thanks for spotting this - we will get this corrected.  The disk extension task should have stated to use F, not E.
